# Autogenerated file, do not edit!
# code fingerprint:
# 2.3.100+cpu_2a692c4_97ff6cfd9c86c5c09d7ce775ab64ec5c99230f5d_Release

__version__ = "2.3.100+cpu"
__ipex_gitrev__ = "2a692c4"
__torch_gitrev__ = ""
__gpu_onednn_gitrev__ = ""
__cpu_ideep_gitrev__ = "d64f9a991dbaf02149ef892a938b552065bccdf9"
__build_type__ = "Release"
