# coding: utf-8

"""
    Collibra Protect API

    This API allows you to manage groups.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import collibra_protect
from collibra_protect.models.add_data_source_request import AddDataSourceRequest  # noqa: E501
from collibra_protect.rest import ApiException


class TestAddDataSourceRequest(unittest.TestCase):
    """AddDataSourceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddDataSourceRequest(self):
        """Test AddDataSourceRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = collibra_protect.models.add_data_source_request.AddDataSourceRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
