# Generated by Django 5.0.6 on 2024-06-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djako_plugin_ya_metrics', '0004_alter_yandexmetrikacounterwidget_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yandexmetrikawidgetstyle',
            name='chart_type',
            field=models.CharField(default='line', max_length=32, verbose_name='Тип диаграммы'),
        ),
    ]
