# Generated by Django 3.2.5 on 2023-08-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xj_thread', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name_plural': '01. 信息 - 基本信息'},
        ),
        migrations.AlterModelOptions(
            name='threadcategory',
            options={'verbose_name_plural': '02. 信息 - 主要类别'},
        ),
        migrations.AlterModelOptions(
            name='threadclassify',
            options={'verbose_name_plural': '03. 信息 - 分类'},
        ),
        migrations.AlterModelOptions(
            name='threadextenddata',
            options={'verbose_name_plural': '06. 信息 - 扩展数据'},
        ),
        migrations.AlterModelOptions(
            name='threadextendfield',
            options={'verbose_name_plural': '05. 信息 - 扩展字段'},
        ),
        migrations.AlterModelOptions(
            name='threadimageauth',
            options={'verbose_name_plural': '09. 信息 - 图片权限'},
        ),
        migrations.AlterModelOptions(
            name='threadshow',
            options={'verbose_name_plural': '04. 信息 - 展示类型'},
        ),
        migrations.AlterModelOptions(
            name='threadstatistic',
            options={'verbose_name': '10. 信息 - 信息统计', 'verbose_name_plural': '10. 信息 - 信息统计'},
        ),
        migrations.AlterModelOptions(
            name='threadtag',
            options={'verbose_name_plural': '07. 信息 - 标签类型'},
        ),
        migrations.AlterModelOptions(
            name='threadtagmapping',
            options={'verbose_name_plural': '08. 信息 - 标签映射'},
        ),
        migrations.RemoveField(
            model_name='threadtagmapping',
            name='tag_id',
        ),
        migrations.RemoveField(
            model_name='threadtagmapping',
            name='thread_id',
        ),
        migrations.AddField(
            model_name='thread',
            name='content_coding',
            field=models.CharField(blank=True, choices=[('TEXT', '文本(支持换行)'), ('HTML', 'HTML超文本语言'), ('MARKDOWN', 'MD标记语言'), ('UBB', 'UBB标记语言')], max_length=8, null=True, verbose_name='内容译码类型'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='自定义字段-1'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_10',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段-10'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_11',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段-11'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_12',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段-12'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_13',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段-13'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_14',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段-14'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_15',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段-15'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='自定义字段-2'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='自定义字段-3'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='自定义字段-4'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='自定义字段-5'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段-6'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_7',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段-7'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_8',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段-8'),
        ),
        migrations.AddField(
            model_name='thread',
            name='field_9',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段-9'),
        ),
        migrations.AddField(
            model_name='thread',
            name='group_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='分组ID'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_subitem_thread',
            field=models.BooleanField(blank=True, default=0, help_text='是否是主项信息的分项信息', null=True, verbose_name='是否是分项'),
        ),
        migrations.AddField(
            model_name='thread',
            name='main_thread',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='主项信息ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xj_thread.thread', verbose_name='主项信息ID'),
        ),
        migrations.AddField(
            model_name='thread',
            name='region_code',
            field=models.CharField(blank=True, help_text='行政编码格式：省(2), 市(2), 区县(2), 乡镇街道(3), 村(3)', max_length=12, null=True, verbose_name='所属行政区划编码'),
        ),
        migrations.AddField(
            model_name='thread',
            name='remark',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_no',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='信息编号'),
        ),
        migrations.AddField(
            model_name='threadcategory',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='前端配置'),
        ),
        migrations.AddField(
            model_name='threadextendfield',
            name='default',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='默认值'),
        ),
        migrations.AddField(
            model_name='threadextendfield',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='threadtag',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, help_text='如果是私人标签则不为空，如果为0代表公域标签。', null=True, verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='threadtagmapping',
            name='statistic',
            field=models.ForeignKey(blank=True, db_column='statistic_id', db_constraint=False, help_text='统计关联', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thread_statistic', to='xj_thread.threadstatistic', verbose_name='统计ID'),
        ),
        migrations.AddField(
            model_name='threadtagmapping',
            name='tag',
            field=models.ForeignKey(blank=True, db_column='tag_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xj_thread.threadtag', verbose_name='标签ID'),
        ),
        migrations.AddField(
            model_name='threadtagmapping',
            name='thread',
            field=models.ForeignKey(blank=True, db_column='thread_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thread', to='xj_thread.thread', verbose_name='信息ID'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='access_level',
            field=models.IntegerField(blank=True, choices=[(0, '所有人 EVERYONE'), (1, '访客 VISITOR'), (2, '会员 STAFF'), (3, '主管 MANAGER'), (4, '管理员 ADMINISTRATOR'), (5, '超级管理员 SUPER_ADMINISTRATOR'), (11, '好友 FRIEND'), (12, '指定人 SOMEONE'), (13, '指定群组 GROUP'), (14, '仅与用户 EACH_OTHER'), (15, '私人可见 PRIVATE'), (21, '指定角色 ROLE'), (31, '阅后即焚(只能看一次) BURN_AFTER_READ'), (32, '已焚毁 BURNED_AND_READ')], null=True, verbose_name='访问级别'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='author',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='作者/主办者'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xj_thread.threadcategory', verbose_name='类别ID'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='classify',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xj_thread.threadclassify', verbose_name='分类ID'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='ip',
            field=models.GenericIPAddressField(blank=True, default='192.168.2.251', null=True, verbose_name='网络IP'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_original',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否原创/独有权'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='link',
            field=models.URLField(blank=True, help_text='跳转/参考链接', max_length=1024, null=True, verbose_name='跳转/参考链接'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='logs',
            field=models.JSONField(blank=True, null=True, verbose_name='日志'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name='价格/原价'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='show',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='如果没有传入显示类型，则使用分类表中的默认显示类型', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xj_thread.threadshow', verbose_name='展示ID'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='子标题'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='threadcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='类别名称'),
        ),
        migrations.AlterField(
            model_name='threadcategory',
            name='need_auth',
            field=models.BooleanField(blank=True, help_text='类别是否登录后才能查看', null=True, verbose_name='是否需登录权限'),
        ),
        migrations.AlterField(
            model_name='threadcategory',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xj_thread.threadcategory', verbose_name='父类类别'),
        ),
        migrations.AlterField(
            model_name='threadcategory',
            name='platform_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='平台码'),
        ),
        migrations.AlterField(
            model_name='threadcategory',
            name='value',
            field=models.CharField(help_text='类别唯一标识值是标识类别的唯一选项', max_length=50, verbose_name='类别标识值'),
        ),
        migrations.AlterField(
            model_name='threadclassify',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xj_thread.threadcategory', verbose_name='所属类别'),
        ),
        migrations.AlterField(
            model_name='threadclassify',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='前端配置'),
        ),
        migrations.AlterField(
            model_name='threadclassify',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='threadclassify',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xj_thread.threadclassify', verbose_name='父分类'),
        ),
        migrations.AlterField(
            model_name='threadclassify',
            name='show',
            field=models.ForeignKey(blank=True, db_column='show_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xj_thread.threadshow', verbose_name='默认展示ID'),
        ),
        migrations.AlterField(
            model_name='threadclassify',
            name='value',
            field=models.CharField(max_length=50, unique=True, verbose_name='分类标识值'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_1 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_10',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_10 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_11',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_11 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_12',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_12 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_13',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_13 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_14',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_14 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_15',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_15 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_16',
            field=models.TextField(blank=True, null=True, verbose_name='自定义字段_16 (长文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_17',
            field=models.TextField(blank=True, null=True, verbose_name='自定义字段_17 (长文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_18',
            field=models.TextField(blank=True, null=True, verbose_name='自定义字段_18 (长文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_19',
            field=models.TextField(blank=True, null=True, verbose_name='自定义字段_19 (长文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_2 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_20',
            field=models.TextField(blank=True, null=True, verbose_name='自定义字段_20 (长文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_3 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_4 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_5 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_6 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_7',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_7 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_8',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_8 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextenddata',
            name='field_9',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段_9 (文本)'),
        ),
        migrations.AlterField(
            model_name='threadextendfield',
            name='category',
            field=models.ForeignKey(db_column='category_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xj_thread.threadcategory', verbose_name='类别ID'),
        ),
        migrations.AlterField(
            model_name='threadextendfield',
            name='field_index',
            field=models.CharField(choices=[('field_1', '自定义字段1 (字符)'), ('field_2', '自定义字段2 (字符)'), ('field_3', '自定义字段3 (字符)'), ('field_4', '自定义字段4 (字符)'), ('field_5', '自定义字段5 (字符)'), ('field_6', '自定义字段6 (字符)'), ('field_7', '自定义字段7 (字符)'), ('field_8', '自定义字段8 (字符)'), ('field_9', '自定义字段9 (字符)'), ('field_10', '自定义字段10 (字符)'), ('field_11', '自定义字段11 (字符)'), ('field_12', '自定义字段12 (字符)'), ('field_13', '自定义字段13 (字符)'), ('field_14', '自定义字段14 (字符)'), ('field_15', '自定义字段15 (字符)'), ('field_16', '自定义字段16 (长文本)'), ('field_17', '自定义字段17 (长文本)'), ('field_18', '自定义字段18 (长文本)'), ('field_19', '自定义字段19 (长文本)'), ('field_20', '自定义字段20 (长文本)')], max_length=255, verbose_name='映射的字段索引'),
        ),
        migrations.AlterField(
            model_name='threadextendfield',
            name='type',
            field=models.CharField(blank=True, choices=[('bool', '布尔型-bool'), ('int', '整型-int'), ('float', '浮点型-float'), ('number', '数字类型-number'), ('string', '字符串型-string'), ('text', '长文本型-text'), ('plain', '普通文字-plain'), ('input', '输入框-plain'), ('password', '密码框-password'), ('textarea', '多行文本框-textarea'), ('editor', '富文本编辑器-editor'), ('switch', '开关切换-switch'), ('select', '选择框-select'), ('radio', '单选框-radio'), ('checkbox', '多选框-checkbox'), ('cascader', '级联选择器-cascader'), ('color', '色彩选择器-color'), ('slot', '插槽-slot'), ('image', '图片-image'), ('audio', '音频-audio'), ('video', '视频-video'), ('file', '文件-file'), ('upload', '上传类型-upload'), ('time', ' 时间-time'), ('datetime', '日期时间-datetime'), ('date', '日期-date'), ('month', '月份-month'), ('year', '年-year')], max_length=32, null=True, verbose_name='字段类型'),
        ),
        migrations.AlterField(
            model_name='threadextendfield',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='字段标签'),
        ),
        migrations.AlterField(
            model_name='threadshow',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='前端配置'),
        ),
        migrations.AlterField(
            model_name='threadshow',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='展示类型名'),
        ),
        migrations.AlterField(
            model_name='threadshow',
            name='value',
            field=models.CharField(max_length=50, verbose_name='展示类型值'),
        ),
        migrations.AlterField(
            model_name='threadstatistic',
            name='thread_id',
            field=models.OneToOneField(db_column='thread_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='xj_thread.thread', verbose_name='信息ID'),
        ),
        migrations.CreateModel(
            name='ThreadMainExtendField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='信息ID')),
                ('field_index', models.CharField(choices=[('field_1', '自定义字段1 (数字)'), ('field_2', '自定义字段2 (数字)'), ('field_3', '自定义字段3 (数字)'), ('field_4', '自定义字段4 (数字)'), ('field_5', '自定义字段5 (数字)'), ('field_6', '自定义字段6 (字符)'), ('field_7', '自定义字段7 (字符)'), ('field_8', '自定义字段8 (字符)'), ('field_9', '自定义字段9 (字符)'), ('field_10', '自定义字段10 (字符)'), ('field_11', '自定义字段11 (字符)'), ('field_12', '自定义字段12 (字符)'), ('field_13', '自定义字段13 (字符)'), ('field_14', '自定义字段14 (字符)'), ('field_15', '自定义字段15 (字符)')], max_length=8, verbose_name='映射的字段索引')),
                ('field', models.CharField(max_length=32, verbose_name='自定义字段')),
                ('value', models.CharField(blank=True, max_length=32, null=True, verbose_name='字段标签')),
                ('default', models.CharField(blank=True, max_length=2048, null=True, verbose_name='默认值')),
                ('type', models.CharField(blank=True, choices=[('bool', '布尔型-bool'), ('int', '整型-int'), ('float', '浮点型-float'), ('number', '数字类型-number'), ('string', '字符串型-string'), ('text', '长文本型-text'), ('plain', '普通文字-plain'), ('input', '输入框-plain'), ('password', '密码框-password'), ('textarea', '多行文本框-textarea'), ('editor', '富文本编辑器-editor'), ('switch', '开关切换-switch'), ('select', '选择框-select'), ('radio', '单选框-radio'), ('checkbox', '多选框-checkbox'), ('cascader', '级联选择器-cascader'), ('color', '色彩选择器-color'), ('slot', '插槽-slot'), ('image', '图片-image'), ('audio', '音频-audio'), ('video', '视频-video'), ('file', '文件-file'), ('upload', '上传类型-upload'), ('time', ' 时间-time'), ('datetime', '日期时间-datetime'), ('date', '日期-date'), ('month', '月份-month'), ('year', '年-year')], max_length=32, null=True, verbose_name='字段类型')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='单位')),
                ('config', models.JSONField(blank=True, default=dict, null=True, verbose_name='前端配置')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('category', models.ForeignKey(db_column='category_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xj_thread.threadcategory', verbose_name='类别ID')),
            ],
            options={
                'verbose_name_plural': '01. 信息 - 主表扩展字段',
                'db_table': 'thread_main_extend_field',
            },
        ),
    ]
