# Generated by Django 4.2.11 on 2024-04-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_chargedinterests_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyissue',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=7, null=True, verbose_name='Сумма'),
        ),
    ]
