# coding: utf-8

"""
    Collibra Catalog Database Registration API

    This API allows you to manage the **metadata ingestion**, **profiling**, and **classification** of databases via Edge.  It provides the following functionalities: - Query and synchronize the database and schema connections. - Register the databases to be ingested, profiled and classified. - Configure and trigger the metadata ingestion of databases. - Configure and trigger the profiling and classification of databases.   # noqa: E501

    OpenAPI spec version: 1.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import collibra_catalog_database_registration
from collibra_catalog_database_registration.api.database_api import DatabaseApi  # noqa: E501
from collibra_catalog_database_registration.rest import ApiException


class TestDatabaseApi(unittest.TestCase):
    """DatabaseApi unit test stubs"""

    def setUp(self):
        self.api = DatabaseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_database(self):
        """Test case for add_database

        Create a Database asset  # noqa: E501
        """
        pass

    def test_change_database(self):
        """Test case for change_database

        Change a Database asset  # noqa: E501
        """
        pass

    def test_find_databases(self):
        """Test case for find_databases

        Find Database assets  # noqa: E501
        """
        pass

    def test_get_database(self):
        """Test case for get_database

        Get a Database asset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
