# coding: utf-8

"""
    Collibra Catalog Cloud Ingestions API

    <p>The Catalog Cloud Ingestions API offers functionality related to the catalog product.<br/> It is mainly focused on facilitating the ingestion of information into Catalog. The API enables users to more easily connect Catalog to sources that are not necessarily natively supported in the product. </p>  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import collibra_catalog_cloud_ingestions
from collibra_catalog_cloud_ingestions.models.schedule import Schedule  # noqa: E501
from collibra_catalog_cloud_ingestions.rest import ApiException


class TestSchedule(unittest.TestCase):
    """Schedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchedule(self):
        """Test Schedule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = collibra_catalog_cloud_ingestions.models.schedule.Schedule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
