# coding: utf-8

"""
    LEO Station Keeping API

    This mission allows to estimate the cost of station keeping maneuvers needed  to counter the effects of the atmospheric drag on the semi-major axis of a  spacecraft in low Earth orbit (up to an altitude of 1000 km).   <b>CHANGELOG</b> <ul>   <li><b>1.0.0</b> - 2024-06-07 - First version of the API</li> </ul> 

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leo_station_keeping.models.thrust_arcs_position import ThrustArcsPosition

class TestThrustArcsPosition(unittest.TestCase):
    """ThrustArcsPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testThrustArcsPosition(self):
        """Test ThrustArcsPosition"""
        # inst = ThrustArcsPosition()

if __name__ == '__main__':
    unittest.main()
