
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-25T11:22:46-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "05a18c5e15ba3bea57922c7f0a5b510b3b9b8c62",
 "version": "1.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
