# coding: utf-8

"""
    Collibra Catalog External Profiling Upload API

    <p>This API is used to manually push profiling data.</p>  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import collibra_catalog_external_profiling_upload
from collibra_catalog_external_profiling_upload.models.categorical_metadata import CategoricalMetadata  # noqa: E501
from collibra_catalog_external_profiling_upload.rest import ApiException


class TestCategoricalMetadata(unittest.TestCase):
    """CategoricalMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCategoricalMetadata(self):
        """Test CategoricalMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = collibra_catalog_external_profiling_upload.models.categorical_metadata.CategoricalMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
