# Generated by Django 3.0.8 on 2021-07-01 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loducode_utils', '0002_auto_20210318_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='user who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creation user'),
        ),
        migrations.AlterField(
            model_name='city',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='user who performed the update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='update user'),
        ),
    ]
