# coding: utf-8

"""
    Collibra Catalog Classification API

    Version 2 of the Catalog Classification API offers functionality related to the classification process and facilitates searching for and managing the associations between a data class and a data category. Use version 1 of the API for managing classifications and legacy data classes.   # noqa: E501

    OpenAPI spec version: 2.0.0-unstable
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import collibra_catalog_classification
from collibra_catalog_classification.api.classification_data_category_api import ClassificationDataCategoryApi  # noqa: E501
from collibra_catalog_classification.rest import ApiException


class TestClassificationDataCategoryApi(unittest.TestCase):
    """ClassificationDataCategoryApi unit test stubs"""

    def setUp(self):
        self.api = ClassificationDataCategoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_connect_data_category_data_class(self):
        """Test case for connect_data_category_data_class

        Associate data class with data category  # noqa: E501
        """
        pass

    def test_disconnect_data_category_data_class(self):
        """Test case for disconnect_data_category_data_class

        Remove existing association between a data class and a data category  # noqa: E501
        """
        pass

    def test_get_association_data_class_data_category(self):
        """Test case for get_association_data_class_data_category

        Retrieve the association with a data category and a data class.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
