# coding: utf-8

"""
    Collibra Catalog Classification API

    <p>The Catalog API offers functionality related to the catalog product.<br/> It is mainly focused on facilitating the ingestion of information into Catalog. The API enables users to more easily connect Catalog to sources that are not necessarily natively supported in the product. </p>  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import collibra_catalog_classification
from collibra_catalog_classification.models.find_classifications_request import FindClassificationsRequest  # noqa: E501
from collibra_catalog_classification.rest import ApiException


class TestFindClassificationsRequest(unittest.TestCase):
    """FindClassificationsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFindClassificationsRequest(self):
        """Test FindClassificationsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = collibra_catalog_classification.models.find_classifications_request.FindClassificationsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
