# coding: utf-8

"""
    Collibra Search API

    <p>The Search API allows you to create your own integration with the Collibra Search Engine.<br /> Find your data!</p>  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SearchFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field': 'str',
        'values': 'list[str]'
    }

    attribute_map = {
        'field': 'field',
        'values': 'values'
    }

    def __init__(self, field=None, values=None):  # noqa: E501
        """SearchFilter - a model defined in Swagger"""  # noqa: E501
        self._field = None
        self._values = None
        self.discriminator = None
        if field is not None:
            self.field = field
        if values is not None:
            self.values = values

    @property
    def field(self):
        """Gets the field of this SearchFilter.  # noqa: E501

        The reference field for the filter. You must also provide at least a value for each reference field.<br /> Possible values are `community`, `domain`, `domainType`, `assetType`, `status`, `createdBy`, `lastModifiedOn`, `createdOn`, `tags`.<br /> Use in conjunction with `values`.  # noqa: E501

        :return: The field of this SearchFilter.  # noqa: E501
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this SearchFilter.

        The reference field for the filter. You must also provide at least a value for each reference field.<br /> Possible values are `community`, `domain`, `domainType`, `assetType`, `status`, `createdBy`, `lastModifiedOn`, `createdOn`, `tags`.<br /> Use in conjunction with `values`.  # noqa: E501

        :param field: The field of this SearchFilter.  # noqa: E501
        :type: str
        """

        self._field = field

    @property
    def values(self):
        """Gets the values of this SearchFilter.  # noqa: E501

        A list of values for the reference field. You must provide at least one value for each reference filed.<br /> Works in conjunction with `filed`.<br /> <br /> Possible values for `community`, `domain`, `domainType`, `assetType`, `status` and `createdBy` are one or more UUIDs.<br /> <br /> Possible values for `lastModifiedOn` and `createdOn` are `LAST_24H`, `LAST_7D`, `LAST_30D`, `LAST_365D`, `OLDER_THAN_365D`.<br /> <br /> Possible values for `tags` are one or more string values.  # noqa: E501

        :return: The values of this SearchFilter.  # noqa: E501
        :rtype: list[str]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this SearchFilter.

        A list of values for the reference field. You must provide at least one value for each reference filed.<br /> Works in conjunction with `filed`.<br /> <br /> Possible values for `community`, `domain`, `domainType`, `assetType`, `status` and `createdBy` are one or more UUIDs.<br /> <br /> Possible values for `lastModifiedOn` and `createdOn` are `LAST_24H`, `LAST_7D`, `LAST_30D`, `LAST_365D`, `OLDER_THAN_365D`.<br /> <br /> Possible values for `tags` are one or more string values.  # noqa: E501

        :param values: The values of this SearchFilter.  # noqa: E501
        :type: list[str]
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
