# This file was auto-generated by Fern from our API Definition.

import typing

InstanceStatus = typing.Union[
    typing.Literal["running", "pending", "unhealthy", "shutting_down", "terminated", "stopping", "stopped"], typing.Any
]
