DYNRM_SUCCESS = 0
DYNRM_ERR_NOT_FOUND = 1
DYNRM_ERR_BAD_PARAM = 2
DYNRM_ERR_NO_PERM = 3
DYNRM_ERR_EXISTS = 4
DYNRM_ERR_NOT_IMPLEMENTED = 5

DYNRM_MCA_SUCCESS = DYNRM_SUCCESS
DYNRM_MCA_ERR_NOT_FOUND = DYNRM_ERR_NOT_FOUND
DYNRM_MCA_ERR_BAD_PARAM = DYNRM_ERR_BAD_PARAM
DYNRM_MCA_ERR_NO_PERM = DYNRM_ERR_NO_PERM
DYNRM_MCA_ERR_EXISTS = DYNRM_ERR_EXISTS
DYNRM_MCA_ERR_NOT_IMPLEMENTED = DYNRM_ERR_NOT_IMPLEMENTED
