
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-25T08:50:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e946addb88370cb8ed8cc0c8f0ba9813589311e",
 "version": "1.0.88"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
